/**
 * Regenerates the base64-embedded invoice font module from the committed TTF.
 * Run manually only when the font file changes:
 *
 *   node scripts/embed-font.ts
 *
 * The generated module (fonts/dejavu-sans.ts) is committed so the renderer
 * needs no filesystem access at runtime — it works identically in vitest,
 * node scripts and a Vercel function. See modules/invoice/README.md.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const fontsDir = path.resolve(import.meta.dirname, '../src/lib/modules/invoice/fonts');
const ttf = readFileSync(path.join(fontsDir, 'DejaVuSans.ttf'));
const base64 = ttf.toString('base64');

const out = `// GENERATED by scripts/embed-font.ts from fonts/DejaVuSans.ttf — do not edit.
// DejaVu Sans (Bitstream Vera license + public-domain additions, see ./LICENSE),
// embedded as base64 so PDF rendering needs no runtime filesystem access.
export const DEJAVU_SANS_TTF_BASE64 =
	'${base64}';
`;
writeFileSync(path.join(fontsDir, 'dejavu-sans.ts'), out);
console.log(
	`fonts/dejavu-sans.ts written (${ttf.length} bytes TTF, ${base64.length} chars base64)`
);
