import { describe, expect, it } from 'vitest';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { formatCents } from '../../util/money.ts';
import { cartTotalCents } from './cart.ts';
import { NIGHT_MAP_SKUS, NIGHT_SEGMENT_KEYS } from './night-map.ts';
import { findShippingOption, shippingOptionsForCart, type ShippingSettings } from './shipping.ts';

// The night map names real catalogue SKUs: every entry must match a COMMITTED
// product bundle (content/sleep, generated by products-from-initialdata.ts).
// A renamed or dropped product fails here instead of shipping a dead link.

const SLEEP_DIR = path.resolve(import.meta.dirname, '../../../../../../content/sleep');

async function committedProducts(): Promise<Map<string, { name: string; priceCents: number }>> {
	const map = new Map<string, { name: string; priceCents: number }>();
	for (const file of await readdir(SLEEP_DIR)) {
		if (!file.endsWith('.json')) continue;
		const bundle = JSON.parse(await readFile(path.join(SLEEP_DIR, file), 'utf8')) as {
			type: string;
			product?: { slug: string; name: string; priceCents: number; status: string };
		};
		if (bundle.type !== 'product') continue;
		expect(bundle.product?.status).toBe('active');
		map.set(bundle.product!.slug, bundle.product!);
	}
	return map;
}

describe('NIGHT_MAP_SKUS', () => {
	it('covers exactly the four night segments with 2–3 SKUs each', () => {
		expect(Object.keys(NIGHT_MAP_SKUS).toSorted()).toEqual([...NIGHT_SEGMENT_KEYS].toSorted());
		for (const key of NIGHT_SEGMENT_KEYS) {
			expect(NIGHT_MAP_SKUS[key].length, key).toBeGreaterThanOrEqual(2);
			expect(NIGHT_MAP_SKUS[key].length, key).toBeLessThanOrEqual(3);
		}
	});

	it('every entry is a committed active product and its label is the SKU name', async () => {
		const products = await committedProducts();
		expect(products.size).toBe(33);

		const seen = new Set<string>();
		for (const key of NIGHT_SEGMENT_KEYS) {
			for (const { slug, label } of NIGHT_MAP_SKUS[key]) {
				const product = products.get(slug);
				expect(product, `${key}: "${slug}" is not a committed product`).toBeDefined();
				// The label is the product name minus its pack-size suffix — a
				// rename in the catalogue must break this pin.
				const named =
					product!.name === label || product!.name.startsWith(`${label},`);
				expect(named, `${key}: label "${label}" does not name "${product!.name}"`).toBe(true);
				expect(seen.has(slug), `"${slug}" appears in two segments`).toBe(false);
				seen.add(slug);
			}
		}
	});
});

describe('cart money math at the catalogue boundary (BS-6 §3)', () => {
	// Real captured prices: Magtein 216 lei, Magneziu Taurat and Magneziu
	// Citrat 49 lei each — all integer bani through cart, shipping and
	// formatting; no float ever touches an amount.
	const shippingSettings: ShippingSettings = {
		'shop.freeShippingThresholdBani': 30000,
		'shop.shippingStandardName': 'Curier standard',
		'shop.shippingStandardPriceBani': 1999,
		'shop.shippingStandardEta': '1-3 zile lucrătoare',
		'shop.shippingExpressName': '',
		'shop.shippingExpressPriceBani': 0,
		'shop.shippingExpressEta': ''
	};

	it('216 lei + two 49 lei items cross the free-shipping threshold exactly', async () => {
		const products = await committedProducts();
		const magtein = products.get('magtein-magneziu-treonat-90-capsule')!;
		const taurat = products.get('magnesium-taurate')!;
		const citrat = products.get('magnesium-citrate')!;
		expect(magtein.priceCents).toBe(21600);
		expect(taurat.priceCents).toBe(4900);
		expect(citrat.priceCents).toBe(4900);

		const goods = cartTotalCents([
			{ priceCents: magtein.priceCents, qty: 1 },
			{ priceCents: taurat.priceCents, qty: 1 },
			{ priceCents: citrat.priceCents, qty: 1 }
		]);
		expect(goods).toBe(31400);
		expect(formatCents(goods)).toBe('314,00 lei');

		// Above the 300-lei threshold: standard shipping is free, total unchanged.
		const free = findShippingOption(shippingOptionsForCart(shippingSettings, goods), 'standard')!;
		expect(free.priceCents).toBe(0);
		expect(free.freeOverThreshold).toBe(true);
		expect(formatCents(goods + free.priceCents)).toBe('314,00 lei');

		// Drop one 49-lei item: 265 lei falls below the threshold and pays
		// 19,99 shipping — 284,99 lei, formatted with integer math only.
		const below = cartTotalCents([
			{ priceCents: magtein.priceCents, qty: 1 },
			{ priceCents: taurat.priceCents, qty: 1 }
		]);
		expect(below).toBe(26500);
		const paid = findShippingOption(shippingOptionsForCart(shippingSettings, below), 'standard')!;
		expect(paid.priceCents).toBe(1999);
		expect(formatCents(below + paid.priceCents)).toBe('284,99 lei');

		// Exactly AT the threshold counts as free (>=, not >).
		const atThreshold = findShippingOption(
			shippingOptionsForCart(shippingSettings, 30000),
			'standard'
		)!;
		expect(atThreshold.priceCents).toBe(0);
	});
});
