// Ownership ledger for the generated bundles in `content/sleep/` (review M-9).
//
// The regeneration scripts (`scripts/articles-from-initialdata.ts`,
// `scripts/products-from-initialdata.ts`) must delete bundles that stopped
// being generated (a slug rename would otherwise leave the old file behind and
// re-import under the dead slug) — but they must NEVER delete a hand-authored
// bundle a maintainer exported into the same directory. Filename patterns
// can't tell the two apart, so ownership is explicit: each run records the
// filenames it generated in a committed manifest (`.generated-manifest`, no
// `.json` suffix so the content importer never reads it), and the next run
// deletes only files the PREVIOUS run generated and this run did not.
//
// Pure data logic only — the scripts own the filesystem side.

export type GeneratedBundleType = 'article' | 'product';

/** Filenames each script generated on its last run, per bundle type. */
export type GeneratedManifest = Record<GeneratedBundleType, string[]>;

export const GENERATED_MANIFEST_NAME = '.generated-manifest';

const EMPTY: GeneratedManifest = { article: [], product: [] };

/**
 * Parse a manifest file's JSON. Tolerant by design: a missing/malformed
 * manifest yields an EMPTY one (the sweep then deletes nothing — the safe
 * failure mode for a ledger whose only job is authorizing deletions).
 */
export function parseGeneratedManifest(raw: unknown): GeneratedManifest {
	if (typeof raw !== 'object' || raw === null) return EMPTY;
	const record = raw as Record<string, unknown>;
	const list = (value: unknown): string[] =>
		Array.isArray(value) ? value.filter((v): v is string => typeof v === 'string') : [];
	return { article: list(record.article), product: list(record.product) };
}

/**
 * Files the running script may delete: generated by the previous run (per the
 * manifest), of the script's own type, no longer generated now, and still
 * present on disk. Anything absent from the manifest is not ours to touch.
 */
export function staleGeneratedFiles(
	manifest: GeneratedManifest,
	type: GeneratedBundleType,
	regenerated: readonly string[],
	existing: readonly string[]
): string[] {
	const keep = new Set(regenerated);
	const present = new Set(existing);
	return manifest[type].filter((file) => !keep.has(file) && present.has(file));
}

/** The next manifest: this run's filenames for `type`, other types untouched. */
export function updateGeneratedManifest(
	manifest: GeneratedManifest,
	type: GeneratedBundleType,
	regenerated: readonly string[]
): GeneratedManifest {
	return { ...manifest, [type]: [...regenerated].sort() };
}

/** Serialized manifest file content (stable formatting for clean diffs). */
export function serializeGeneratedManifest(manifest: GeneratedManifest): string {
	return JSON.stringify({ article: manifest.article, product: manifest.product }, null, '\t') + '\n';
}
