import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { count, eq, sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb, type Db } from '../../db/client.ts';
import { seedPillars } from '../../db/seed.ts';
import { articlePillars, articles } from '../blog/schema.ts';
import { storageConfigFromEnv } from '../media/env.ts';
import { createStorage } from '../media/storage.ts';
import type { ContentDeps } from './export.ts';
import { importContentDirs } from './init.ts';

// BS-4 acceptance: the COMMITTED `content/sleep` bundles (generated by
// `scripts/articles-from-initialdata.ts`) import cleanly into a fresh
// database, re-import idempotently, and never carry the ENGLISH working
// copy from `.initialData/topics.json`.

const ROOT = path.resolve(import.meta.dirname, '../../../../../..');
const SLEEP_DIR = path.join(ROOT, 'content/sleep');
const TOPICS_FILE = path.join(ROOT, '.initialData/topics.json');

let db: Db;
let deps: ContentDeps;

beforeAll(async () => {
	const url = process.env.TEST_DATABASE_URL;
	if (!url) throw new Error('TEST_DATABASE_URL is not set — see .env.example');
	const storageCfg = storageConfigFromEnv(process.env);
	if (!storageCfg.endpoint) {
		throw new Error('S3_* env vars are not set — start `docker compose up -d`');
	}

	db = createDb(url);
	await db.execute(sql`drop schema if exists public cascade`);
	await db.execute(sql`drop schema if exists drizzle cascade`);
	await db.execute(sql`create schema public`);
	await migrate(db, { migrationsFolder: path.resolve(import.meta.dirname, '../../../../drizzle') });
	await seedPillars(db, ['somn']);

	const storage = createStorage(storageCfg);
	await storage.ensureBucket();
	deps = { db, storage };
});

afterAll(async () => {
	await db?.$client.end();
});

async function articleCount(): Promise<number> {
	const [row] = await db.select({ n: count() }).from(articles);
	return row.n;
}

describe('the committed content/sleep article bundles', () => {
	it('imports all 40 into a fresh database', async () => {
		const files = (await readdir(SLEEP_DIR)).filter((f) => f.endsWith('.json'));
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed, JSON.stringify(summary.results.filter((r) => !r.ok))).toBe(0);
		expect(summary.imported).toBe(files.length);

		expect(await articleCount()).toBe(40);
		const [published] = await db
			.select({ n: count() })
			.from(articles)
			.where(eq(articles.status, 'published'));
		expect(published.n).toBe(40);
		// Every article is pillar-tagged (site visibility runs on pillars).
		const [tagged] = await db.select({ n: count() }).from(articlePillars);
		expect(tagged.n).toBe(40);
	});

	it('spot-checked bodies keep Romanian diacritics and markdown structure', async () => {
		for (const slug of [
			'sistemul-glimfatic-curatenia-creierului',
			'obosit-dar-alert-hyperarousal',
			'tracker-de-somn-ajuta-sau-strica'
		]) {
			const [row] = await db.select().from(articles).where(eq(articles.slug, slug));
			expect(row, slug).toBeDefined();
			expect(row.bodyMd, slug).toMatch(/^## /m);
			expect(row.bodyMd, slug).toMatch(/[ăâîșț]/);
			expect(row.title, slug).not.toMatch(/^# /);
			expect(row.excerpt.length, slug).toBeGreaterThan(0);
			expect(row.seoTitle, slug).toBeTruthy();
			expect(row.seoDescription, slug).toBeTruthy();
		}
	});

	it('re-imports nothing new (idempotent upsert by slug)', async () => {
		const before = await articleCount();
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed).toBe(0);
		expect(await articleCount()).toBe(before);
	});

	it('carries no English text from topics.json', async () => {
		const topics = JSON.parse(await readFile(TOPICS_FILE, 'utf8')) as Array<{
			title: string;
			excerpt: string;
		}>;
		const english = new Set(topics.flatMap((t) => [t.title, t.excerpt]));
		expect(english.size).toBeGreaterThan(0);

		for (const row of await db.select().from(articles)) {
			for (const value of [row.title, row.excerpt, row.seoTitle, row.seoDescription]) {
				expect(english.has(value ?? ''), `"${row.slug}": "${value}"`).toBe(false);
			}
		}
	});
});
