import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { count, eq, sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb, type Db } from '../../db/client.ts';
import { seedPillars } from '../../db/seed.ts';
import { articlePillars, articles } from '../blog/schema.ts';
import { NIGHT_MAP_SKUS } from '../shop/night-map.ts';
import { productPillars, products } from '../shop/schema.ts';
import { formatCents } from '../../util/money.ts';
import { storageConfigFromEnv } from '../media/env.ts';
import { createStorage } from '../media/storage.ts';
import type { ContentDeps } from './export.ts';
import { parseBundle, type ContentBundle } from './bundle.ts';
import { importContent } from './import.ts';
import { importContentDirs } from './init.ts';

// BS-4/BS-6 acceptance: the COMMITTED `content/sleep` bundles (generated by
// `scripts/articles-from-initialdata.ts` and
// `scripts/products-from-initialdata.ts`) import cleanly into a fresh
// database, re-import idempotently, and never carry the English working copy
// from `.initialData/` (topics.json titles/excerpts, zenyth blurbs).

const ROOT = path.resolve(import.meta.dirname, '../../../../../..');
const SLEEP_DIR = path.join(ROOT, 'content/sleep');
const TOPICS_FILE = path.join(ROOT, '.initialData/topics.json');
const ZENYTH_FILE = path.join(ROOT, '.initialData/zenyth-products.json');

let db: Db;
let deps: ContentDeps;

beforeAll(async () => {
	const url = process.env.TEST_DATABASE_URL;
	if (!url) throw new Error('TEST_DATABASE_URL is not set — see .env.example');
	const storageCfg = storageConfigFromEnv(process.env);
	if (!storageCfg.endpoint) {
		throw new Error('S3_* env vars are not set — start `docker compose up -d`');
	}

	db = createDb(url);
	await db.execute(sql`drop schema if exists public cascade`);
	await db.execute(sql`drop schema if exists drizzle cascade`);
	await db.execute(sql`create schema public`);
	await migrate(db, { migrationsFolder: path.resolve(import.meta.dirname, '../../../../drizzle') });
	await seedPillars(db, ['somn']);

	const storage = createStorage(storageCfg);
	await storage.ensureBucket();
	deps = { db, storage };
});

afterAll(async () => {
	await db?.$client.end();
});

async function articleCount(): Promise<number> {
	const [row] = await db.select({ n: count() }).from(articles);
	return row.n;
}

describe('the committed content/sleep article bundles', () => {
	it('imports all 40 into a fresh database', async () => {
		const files = (await readdir(SLEEP_DIR)).filter((f) => f.endsWith('.json'));
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed, JSON.stringify(summary.results.filter((r) => !r.ok))).toBe(0);
		expect(summary.imported).toBe(files.length);

		expect(await articleCount()).toBe(40);
		const [published] = await db
			.select({ n: count() })
			.from(articles)
			.where(eq(articles.status, 'published'));
		expect(published.n).toBe(40);
		// Every article is pillar-tagged (site visibility runs on pillars).
		const [tagged] = await db.select({ n: count() }).from(articlePillars);
		expect(tagged.n).toBe(40);
	});

	it('spot-checked bodies keep Romanian diacritics and markdown structure', async () => {
		for (const slug of [
			'sistemul-glimfatic-curatenia-creierului',
			'obosit-dar-alert-hyperarousal',
			'tracker-de-somn-ajuta-sau-strica'
		]) {
			const [row] = await db.select().from(articles).where(eq(articles.slug, slug));
			expect(row, slug).toBeDefined();
			expect(row.bodyMd, slug).toMatch(/^## /m);
			expect(row.bodyMd, slug).toMatch(/[ăâîșț]/);
			expect(row.title, slug).not.toMatch(/^# /);
			expect(row.excerpt.length, slug).toBeGreaterThan(0);
			expect(row.seoTitle, slug).toBeTruthy();
			expect(row.seoDescription, slug).toBeTruthy();
		}
	});

	it('re-imports nothing new (idempotent upsert by slug)', async () => {
		const before = await articleCount();
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed).toBe(0);
		expect(await articleCount()).toBe(before);
	});

	it('imports the 33 product bundles alongside (BS-6)', async () => {
		// The dir-wide imports above already ran; this pins what they created.
		const [productCount] = await db.select({ n: count() }).from(products);
		expect(productCount.n).toBe(33);
		const [active] = await db
			.select({ n: count() })
			.from(products)
			.where(eq(products.status, 'active'));
		expect(active.n).toBe(33);
		// Every product is pillar-tagged (site visibility runs on pillars).
		const [tagged] = await db.select({ n: count() }).from(productPillars);
		expect(tagged.n).toBe(33);
	});

	it('product rows carry the captured price, test stock and no Stripe wiring', async () => {
		const zenyth = JSON.parse(await readFile(ZENYTH_FILE, 'utf8')) as {
			capturedAt: string;
			products: Array<{ url: string; priceLei: number; blurb: string }>;
		};
		const bySlug = new Map(
			zenyth.products.map((p) => [p.url.split('/').filter(Boolean).pop()!, p])
		);

		const rows = await db.select().from(products);
		expect(rows).toHaveLength(33);
		for (const row of rows) {
			const captured = bySlug.get(row.slug);
			expect(captured, row.slug).toBeDefined();
			// Money: integer bani = captured integer lei × 100.
			expect(row.priceCents, row.slug).toBe(captured!.priceLei * 100);
			expect(row.currency, row.slug).toBe('ron');
			expect(row.stock, row.slug).toBe(25);
			expect(row.stripeProductId, row.slug).toBeNull();
			expect(row.stripePriceId, row.slug).toBeNull();
			expect(row.coverMediaId, row.slug).toBeNull();
			expect(row.gallery, row.slug).toEqual([]);
			// Fresh Romanian description with the price-source line; the captured
			// blurb (partly auto-translated English) never ships. The line is
			// UNLINKED (L-9): no product page grants the supplier a dofollow
			// backlink or a clickable path to buy direct.
			expect(row.descriptionMd, row.slug).toMatch(/[ăâîșț]/);
			expect(row.descriptionMd, row.slug).toContain(`Sursă preț: zenyth.ro, ${zenyth.capturedAt}`);
			expect(row.descriptionMd, row.slug).not.toContain('](https://zenyth.ro');
			if (captured!.blurb.trim()) {
				expect(row.descriptionMd.includes(captured!.blurb.trim()), row.slug).toBe(false);
			}
		}

		// The 216-lei boundary product formats correctly through money.ts.
		const magtein = rows.find((r) => r.slug === 'magtein-magneziu-treonat-90-capsule');
		expect(magtein).toBeDefined();
		expect(formatCents(magtein!.priceCents, magtein!.currency)).toBe('216,00 lei');
	});

	it('re-imports products idempotently (still 33, upsert by slug)', async () => {
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed).toBe(0);
		const [productCount] = await db.select({ n: count() }).from(products);
		expect(productCount.n).toBe(33);
	});

	it('every night-map SKU is an ACTIVE product in the seeded catalogue (M-5)', async () => {
		// The landing load filters chips to active products; on a freshly
		// seeded database ALL 11 must survive — a bundle status change or slug
		// drift fails here, not silently on the landing page.
		const skus = Object.values(NIGHT_MAP_SKUS).flat();
		expect(skus).toHaveLength(11);
		for (const { slug } of skus) {
			const [row] = await db.select().from(products).where(eq(products.slug, slug));
			expect(row, slug).toBeDefined();
			expect(row.status, slug).toBe('active');
		}
	});

	it('carries no English text from topics.json', async () => {
		const topics = JSON.parse(await readFile(TOPICS_FILE, 'utf8')) as Array<{
			title: string;
			excerpt: string;
		}>;
		const english = new Set(topics.flatMap((t) => [t.title, t.excerpt]));
		expect(english.size).toBeGreaterThan(0);

		for (const row of await db.select().from(articles)) {
			for (const value of [row.title, row.excerpt, row.seoTitle, row.seoDescription]) {
				expect(english.has(value ?? ''), `"${row.slug}": "${value}"`).toBe(false);
			}
		}
	});
});

// Review M-7/M-8: the import upsert keys on the stable importKey (slug
// renames update in place) and skips no-op UPDATEs (updated_at survives
// re-seeds). Runs after the corpus tests above, against the same seeded DB.
describe('import identity and updated_at stability (M-7, M-8)', () => {
	async function loadBundle(file: string): Promise<ContentBundle> {
		const parsed = parseBundle(JSON.parse(await readFile(path.join(SLEEP_DIR, file), 'utf8')));
		if (!parsed.ok) throw new Error(parsed.error);
		return parsed.bundle;
	}

	it('a full re-import leaves every updated_at untouched (M-8)', async () => {
		const before = new Map(
			(await db.select().from(articles)).map((r) => [r.id, r.updatedAt.getTime()])
		);
		const beforeProducts = new Map(
			(await db.select().from(products)).map((r) => [r.id, r.updatedAt.getTime()])
		);
		const summary = await importContentDirs(deps, [SLEEP_DIR]);
		expect(summary.failed).toBe(0);
		for (const row of await db.select().from(articles)) {
			expect(row.updatedAt.getTime(), row.slug).toBe(before.get(row.id));
		}
		for (const row of await db.select().from(products)) {
			expect(row.updatedAt.getTime(), row.slug).toBe(beforeProducts.get(row.id));
		}
	});

	it('a changed bundle still updates the row AND bumps updated_at', async () => {
		const bundle = await loadBundle('0010-sistemul-glimfatic-curatenia-creierului.json');
		if (bundle.type !== 'article') throw new Error('expected article');
		const [before] = await db.select().from(articles).where(eq(articles.slug, bundle.article.slug));

		const edited = { ...bundle, article: { ...bundle.article, excerpt: 'Rezumat editat.' } };
		expect((await importContent(deps, edited)).ok).toBe(true);
		const [after] = await db.select().from(articles).where(eq(articles.id, before.id));
		expect(after.excerpt).toBe('Rezumat editat.');
		expect(after.updatedAt.getTime()).toBeGreaterThan(before.updatedAt.getTime());

		// Restore the corpus (and prove the restore write happens too).
		expect((await importContent(deps, bundle)).ok).toBe(true);
		const [restored] = await db.select().from(articles).where(eq(articles.id, before.id));
		expect(restored.excerpt).toBe(bundle.article.excerpt);
	});

	it('an article slug rename updates the SAME row — no orphaned published duplicate (M-7)', async () => {
		const bundle = await loadBundle('0010-sistemul-glimfatic-curatenia-creierului.json');
		if (bundle.type !== 'article') throw new Error('expected article');
		const originalSlug = bundle.article.slug;
		const [before] = await db.select().from(articles).where(eq(articles.slug, originalSlug));
		expect(before.importKey).toBe(bundle.article.importKey);

		const renamed = {
			...bundle,
			article: { ...bundle.article, slug: 'sistemul-glimfatic-redenumit' }
		};
		const outcome = await importContent(deps, renamed);
		expect(outcome.ok && outcome.value.action).toBe('updated');

		// Same row, new slug; the old slug is GONE (pre-fix: two published rows).
		const [after] = await db
			.select()
			.from(articles)
			.where(eq(articles.slug, 'sistemul-glimfatic-redenumit'));
		expect(after.id).toBe(before.id);
		expect(await db.select().from(articles).where(eq(articles.slug, originalSlug))).toEqual([]);
		const [count40] = await db.select({ n: count() }).from(articles);
		expect(count40.n).toBe(40);

		// Rename back for the rest of the suite.
		expect((await importContent(deps, bundle)).ok).toBe(true);
	});

	it('a product slug rename updates the SAME row (M-7)', async () => {
		const bundle = await loadBundle('1320-stress-help-30-capsule-700-mg.json');
		if (bundle.type !== 'product') throw new Error('expected product');
		const [before] = await db.select().from(products).where(eq(products.slug, bundle.product.slug));

		const renamed = { ...bundle, product: { ...bundle.product, slug: 'stress-help-redenumit' } };
		expect((await importContent(deps, renamed)).ok).toBe(true);
		const [after] = await db
			.select()
			.from(products)
			.where(eq(products.slug, 'stress-help-redenumit'));
		expect(after.id).toBe(before.id);
		const [still33] = await db.select({ n: count() }).from(products);
		expect(still33.n).toBe(33);

		expect((await importContent(deps, bundle)).ok).toBe(true);
	});

	it('a legacy keyless row is adopted by slug and stamped with the key (M-7 fallback)', async () => {
		// Simulate a pre-BS-9 database row: same slug, no importKey.
		await db.insert(articles).values({
			id: 'legacy-article-row',
			slug: 'articol-legacy',
			title: 'Vechi',
			status: 'published'
		});
		const bundle = await loadBundle('0010-sistemul-glimfatic-curatenia-creierului.json');
		if (bundle.type !== 'article') throw new Error('expected article');
		const legacy = {
			...bundle,
			article: { ...bundle.article, slug: 'articol-legacy', importKey: 'topic-999' }
		};
		expect((await importContent(deps, legacy)).ok).toBe(true);
		const [adopted] = await db.select().from(articles).where(eq(articles.id, 'legacy-article-row'));
		expect(adopted.importKey).toBe('topic-999');
		expect(adopted.title).toBe(bundle.article.title);

		// …and a keyless (pre-BS-9) bundle must not ERASE a stamped key.
		const keyless = {
			...bundle,
			article: { ...bundle.article, slug: 'articol-legacy', importKey: null }
		};
		expect((await importContent(deps, keyless)).ok).toBe(true);
		const [kept] = await db.select().from(articles).where(eq(articles.id, 'legacy-article-row'));
		expect(kept.importKey).toBe('topic-999');

		await db.delete(articles).where(eq(articles.id, 'legacy-article-row'));
	});
});
